apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: addons
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 2.6.x
    helm:
      version: v3
      values: |-
        podSecurityStandard: baseline

        podSecuritySeverity: medium
        podSecurityPolicies: []
        includeOtherPolicies: []

        includeRestrictedPolicies: []

        failurePolicy: Fail
        validationFailureAction: audit

        validationFailureActionByPolicy: {}
