---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Cluster infrastructure addons
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/alleaffengaffen/banana.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  generators:
  - git:
      repoURL: https://github.com/alleaffengaffen/banana.git
      revision: HEAD
      directories:
      - path: addons/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "addons"
      source:
        repoURL: https://github.com/alleaffengaffen/banana.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
