---
apiVersion: v1
kind: Secret
metadata:
  name: jammy
  namespace: system-upgrade
type: Opaque
stringData:
  kubelet: 1.25.4-00
  kubectl: 1.25.4-00
  kubeadm: 1.25.4-00
  containerd: 1.5.9-0ubuntu3
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)
    apt-get --assume-yes update
    apt-get --assume-yes install \
      kubelet =$(cat $secrets/kubelet) \
      kubectl=$(cat $secrets/kubectl) \
      kubeadm=$(cat $secrets/kubeadm) \
      containerd=$(cat $secrets/containerd)
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: jammy
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/bionic, operator: Exists}
  serviceAccountName: system-upgrade
  secrets:
    - name: jammy
      path: /host/run/system-upgrade/secrets/jammy
  drain:
    force: true
  version: jammy
  upgrade:
    image: ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/bionic/upgrade.sh"]
