apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgC7oWZRmNbXOcTzxW+hdXyabIwBbsEEbDDxicIxWGlfrC8Rkfz6bSk37SirHSPdhhaXQnz9Uz/yVNEwvLm5oq1mI5IMrU4uEiRhIDC79kkv1g8EL6i6WaHdRkvVuOEmSv/8M1mLwBRCmrh9kOjGk4GWOSWocPUPOFmL3Bs8AdlJaFC0NZpeO7mE5xM/qHVcRqAXovqBVnKb8SmOe0bB9BnWAhl9eYKwo0CCYazGMMMDh2NYYUxGQIawVGS99AKE0ALF/BeDM7scuIV9cLUA8Gie/qTDFt3gHSlPMyLQjiJONjzdoxksTZf2cVorgg4bOWV8tqtsyBts2zvn/8eO93YJAn7kczWUSin0VJRwKS836lTQxzutp+fuHfzPB67Ob2fZmuZKiCkOTKOtgVhnWtCzFycZbRsDaYoImMo41tb7y9h9MP1xrVu5aDhgU2Ef7nioe+v2YQwpY/FgkisCI4OF0RzdhyXMJ1wkpaBQTI0xVaK0eiEJAt1+FCMTtung/0aLcabg9SQAW5HQITgAM7McnbCh4R6T+iGbEmp4XVHi1HOgQiA27ldOx7hp4jXKaRxKmhxghvLNVaUnIe5dQ0+alDb+U+M5bcEt3orR2YBni9n7ijEKow4iNjMdvc1juHN2hh6hBDrWfMZiQ9bAw9p6YSOSOfK5D/flVuBqTwLbAin1OvGQrQaEyujyqOXDMz7bYeVu7tWE2OWF9G17sA+Mkt0RwprG16402Xny9gZrjcv37Z6Llj1b
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
