cert-manager:
  global:
    priorityClassName: "system-cluster-critical"

    leaderElection:
      namespace: "cert-manager"

  installCRDs: true

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 1
      memory: 1Gi


  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 1Gi

    networkPolicy:
      enabled: true

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 1Gi

  startupapicheck:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 1Gi
