resources:
- https://github.com/kubereboot/kured/releases/download/1.11.0/kured-1.11.0-dockerhub.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: kured
    namespace: kube-system
  spec:
    template:
      spec:
        containers:
        - name: kured
          command:
          - /usr/bin/kured
          - --time-zone=Europe/Zurich
          - --start-time=10pm
          - --end-time=6am
          - --reboot-days=mon,tue,wed,thu,fri
