kured:

  configuration:
    rebootDays: [mo, tu,we,th,fr]                # only reboot on these days (default [su,mo,tu,we,th,fr,sa])
    endTime: "6am"                   # only reboot before this time of day (default "23:59")
    startTime: "10pm"
    drainTimeout: ""              # timeout after which the drain is aborted (default: 0, infinite time)
    timeZone: "Europe/Zurich"                  # time-zone to use (valid zones from "time" golang package)
    annotateNodes: true

  resources:
    limits:
      cpu: 5m
      memory: 48Mi
    requests:
      cpu: 1m
      memory: 16Mi
