argo-cd:
  global:
    networkPolicy:
      create: true

  configs:
    cm:
      url: "https://cd.tools.alleaffengaffen.ch"
      server.rbac.log.enforce.enable: "true"
      exec.enabled: "true"
      admin.enabled: "true"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: 26be52c1bdb04a4d6e1f
              clientSecret: $github:clientSecret # references the sealed secret in the templates folder
              orgs:
              - name: alleaffengaffen
    rbac:
      policy.csv: |
        # Grant all members of 'alleaffengaffen:orangutans' admins
        g, alleaffengaffen:orangutans, role:admin
      policy.default: role:readonly

    params:
      controller.status.processors: 20
      controller.operation.processors: 10
      controller.self.heal.timeout.seconds: 5
      controller.repo.server.timeout.seconds: 60

  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      ingressClassName: "nginx"
      hosts:
      - cd.tools.alleaffengaffen.ch
      tls:
      - secretName: argocd-secret
        hosts:
        - cd.tools.alleaffengaffen.ch
      https: true # TLS termination should happen on argocd-server (grpc)
